### ISSUE TITLE
Output ends up in "err" instead of "out" on macos even when exitCode equals 0

### ISSUE THREAD

**Issue by frankforpresident** [PDMLab/docker-compose#252]
When using this package on mac os I've noticed that the output of the command "compose.upAll()" returns an object where exitCode equals 0 and the content ends up in the err instead of out

```
{
  exitCode: 0,
  err: " Container first  Created\n Container second  Created\n Container third  Created\n Container first  Starting\n Container first  Started\n Container second  Starting\n Container second  Started\n Container third  Starting\n Container third  Started\n",
  out: "",
}
```

The containers start perfectly and seem the be fine.

When breaking in the code I do see childProc.stderr event handler is emitting chunks. See: [line:204](https://github.com/PDMLab/docker-compose/blob/master/src/index.ts#L204
)

I'm running on mac os 13.5.1 (22G90)
package version: ^0.24.2
node version: v18.17.1

docker-compose I've used to test this package
```
version: '3'
services:
  first:
    container_name: first
    image: hello-world:latest
  second:
    container_name: second
    image: hello-world:latest
    depends_on:
      - first
  third:
    container_name: third
    image: hello-world:latest
    depends_on:
      - second
```
