### ISSUE TITLE
Get dynamic port

### ISSUE THREAD

**Issue by LarsKumbier** [PDMLab/docker-compose#51]
A `docker-compose.yml` allows to forward a service port to an undefined, ephemeral host port:
```
version: "3"
services:
  database:
    build: .
    ports:
     - "3000"
```
(reference: https://docs.docker.com/compose/compose-file/#ports)

The forwarded host port can be retrieved by the `port` subcommand: https://docs.docker.com/compose/reference/port/
