### ISSUE TITLE
Wait for connection to be available in sql database

### ISSUE THREAD

**Issue by lucas-rudd** [PDMLab/docker-compose#81]
I'm attempting to do something fairly simple.

We have some integration tests that were running against local images of MySQL DBs.

I've dockerized this with a docker-compose file that looks like this

```
version: '3.1'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    command: --explicit_defaults_for_timestamp=ON
    ports:
        - 3306:3306
    restart: always
    volumes:
      - ./scripts/db_scripts:/docker-entrypoint-initdb.d/b.sql
    environment:
      MYSQL_ROOT_PASSWORD: example
      TZ: UTC

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
```

and have tried to do something like this in my DbSetup file (which I would like to set up the docker container for DB tests)

```
export default class DbSetup {
  private static rootDirectory: string = path.join(__dirname, '../../..');
  private static dockerComposeOptions: compose.IDockerComposeOptions = {
    cwd: DbSetup.rootDirectory,
    log: true,
  };

  public static async setup(): Promise<void> {
    // Protection against running tests in non-local environment
    if (process.env.DB_HOST !== 'localhost') {
      throw new Error('DB tests can only be run against localhost');
    }
    await compose.upAll(DbSetup.dockerComposeOptions);
  }
```

This waits for the container to spin up, but it does not wait for the Db to be available to accept connections. Is there a way to await for some sort of health check to pass as well before resolving the promise?
